# Generated by Django 3.0.5 on 2020-04-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('books_count', models.PositiveIntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
            ],
        ),
    ]
