# Generated by Django 3.0.5 on 2020-04-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200413_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books_count',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
