# Generated by Django 3.0.5 on 2020-04-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200417_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
