# Generated by Django 3.0.5 on 2020-04-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200423_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='account/images/default_user_profile_image.png', upload_to='account/images/'),
        ),
    ]
