# Generated by Django 3.0.5 on 2020-04-25 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20200423_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^(?=.{8,30}$)(?![_.])(?!.*[_.]{2})[                                ^[\\s,ء-بت-غف-قل-وَ-ّٕپچژکگھیةكى-ًٍە،؛؟ـ٪٫٬۰-۹]*$                                a-zA-Z0-9._]+(?<![_.])$', message="Username can only contain alphabets, numbers, '_', or '.' in an accepted manner;\nUsername should be 8 to 30 characters long.")]),
        ),
    ]
