# Generated by Django 3.0.5 on 2020-04-25 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20200425_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^(?=.{8,30}$)(?![_.])(?!.*[_.]{2})[ء-بت-غف-قل-وَ-ّٕپچژکگھیةكى-ًٍە،؛؟ـ٪٫٬۰-۹a-zA-Z0-9._]+(?<![_.])$', message="Username can only contain alphabets, numbers, '_', or '.' in an accepted manner;\nUsername should be 8 to 30 characters long.")]),
        ),
    ]
