# Generated by Django 3.0.5 on 2020-04-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20200425_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_retrieval',
            field=models.DateTimeField(null=True, verbose_name='last retrieval'),
        ),
    ]
