# Generated by Django 3.0.5 on 2020-05-15 10:45

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20200502_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=account.models.create_profile_image_upload_path),
        ),
    ]
