# Generated by Django 3.0.5 on 2020-05-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20200515_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='books_count',
        ),
    ]
