# Generated by Django 3.0.5 on 2020-06-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20200624_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_lenders',
            field=models.IntegerField(default=0),
        ),
    ]
