# Generated by Django 3.0.5 on 2020-06-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_user_num_lenders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_rates',
            field=models.IntegerField(default=0),
        ),
    ]
