# Generated by Django 3.0.5 on 2020-05-07 09:35

import book.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('page_num', models.IntegerField()),
                ('edition', models.IntegerField(null=True)),
                ('publisher', models.CharField(blank=True, max_length=30)),
                ('pub_year', models.IntegerField(null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added')),
                ('category_1', models.CharField(choices=[('Novel', 'Novel'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Psychology', 'Psychology'), ('Journal', 'Journal'), ('Poetry', 'Poetry'), ('Education', 'Education'), ('Economics', 'Economics'), ('History', 'History'), ('Law', 'Law'), ('Religious', 'Religious'), ('Life_Style', 'Life Style'), ('Science', 'Science'), ('Social_Science', 'Social Science'), ('Philosophy', 'Philosophy'), ('Comic', 'Comic'), ('Children', 'Children'), ('Art', 'Art'), ('Encyclopedia', 'Encyclopedia'), ('Dictionary', 'Dictionary'), ('Biography', 'Biography'), ('Horror', 'Horror'), ('Crime', 'Crime'), ('Tragedy', 'Tragedy'), ('Fairy_Tail', 'Fairy Tail'), ('Drama', 'Drama'), ('Fable', 'Fable'), ('Humor', 'Humor'), ('Young_Adult', 'Young Adult'), ('Play', 'Play'), ('Political', 'Political'), ('Math', 'Math')], max_length=30)),
                ('category_2', models.CharField(blank=True, choices=[('Novel', 'Novel'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Psychology', 'Psychology'), ('Journal', 'Journal'), ('Poetry', 'Poetry'), ('Education', 'Education'), ('Economics', 'Economics'), ('History', 'History'), ('Law', 'Law'), ('Religious', 'Religious'), ('Life_Style', 'Life Style'), ('Science', 'Science'), ('Social_Science', 'Social Science'), ('Philosophy', 'Philosophy'), ('Comic', 'Comic'), ('Children', 'Children'), ('Art', 'Art'), ('Encyclopedia', 'Encyclopedia'), ('Dictionary', 'Dictionary'), ('Biography', 'Biography'), ('Horror', 'Horror'), ('Crime', 'Crime'), ('Tragedy', 'Tragedy'), ('Fairy_Tail', 'Fairy Tail'), ('Drama', 'Drama'), ('Fable', 'Fable'), ('Humor', 'Humor'), ('Young_Adult', 'Young Adult'), ('Play', 'Play'), ('Political', 'Political'), ('Math', 'Math')], max_length=30)),
                ('category_3', models.CharField(blank=True, choices=[('Novel', 'Novel'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Psychology', 'Psychology'), ('Journal', 'Journal'), ('Poetry', 'Poetry'), ('Education', 'Education'), ('Economics', 'Economics'), ('History', 'History'), ('Law', 'Law'), ('Religious', 'Religious'), ('Life_Style', 'Life Style'), ('Science', 'Science'), ('Social_Science', 'Social Science'), ('Philosophy', 'Philosophy'), ('Comic', 'Comic'), ('Children', 'Children'), ('Art', 'Art'), ('Encyclopedia', 'Encyclopedia'), ('Dictionary', 'Dictionary'), ('Biography', 'Biography'), ('Horror', 'Horror'), ('Crime', 'Crime'), ('Tragedy', 'Tragedy'), ('Fairy_Tail', 'Fairy Tail'), ('Drama', 'Drama'), ('Fable', 'Fable'), ('Humor', 'Humor'), ('Young_Adult', 'Young Adult'), ('Play', 'Play'), ('Political', 'Political'), ('Math', 'Math')], max_length=30)),
                ('image', models.ImageField(null=True, unique=True, upload_to=book.models.create_book_image_upload_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
            ],
        ),
    ]
