# Generated by Django 3.0.5 on 2020-05-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200514_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category_1',
            field=models.CharField(choices=[(0, 'Novel'), (1, 'Mystery'), (2, 'Fantasy'), (3, 'Psychology'), (4, 'Journal'), (5, 'Poetry'), (6, 'Education'), (7, 'Economics'), (8, 'History'), (9, 'Law'), (10, 'Religious'), (11, 'Life_Style'), (12, 'Science'), (13, 'Social_Science'), (14, 'Philosophy'), (15, 'Comic'), (16, 'Children'), (17, 'Art'), (18, 'Encyclopedia'), (19, 'Dictionary'), (20, 'Biography'), (21, 'Horror'), (22, 'Crime'), (23, 'Tragedy'), (24, 'Fairy_Tail'), (25, 'Drama'), (26, 'Fable'), (27, 'Humor'), (28, 'Young_Adult'), (29, 'Play'), (30, 'Political'), (31, 'Math')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='category_2',
            field=models.CharField(blank=True, choices=[(0, 'Novel'), (1, 'Mystery'), (2, 'Fantasy'), (3, 'Psychology'), (4, 'Journal'), (5, 'Poetry'), (6, 'Education'), (7, 'Economics'), (8, 'History'), (9, 'Law'), (10, 'Religious'), (11, 'Life_Style'), (12, 'Science'), (13, 'Social_Science'), (14, 'Philosophy'), (15, 'Comic'), (16, 'Children'), (17, 'Art'), (18, 'Encyclopedia'), (19, 'Dictionary'), (20, 'Biography'), (21, 'Horror'), (22, 'Crime'), (23, 'Tragedy'), (24, 'Fairy_Tail'), (25, 'Drama'), (26, 'Fable'), (27, 'Humor'), (28, 'Young_Adult'), (29, 'Play'), (30, 'Political'), (31, 'Math')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='category_3',
            field=models.CharField(blank=True, choices=[(0, 'Novel'), (1, 'Mystery'), (2, 'Fantasy'), (3, 'Psychology'), (4, 'Journal'), (5, 'Poetry'), (6, 'Education'), (7, 'Economics'), (8, 'History'), (9, 'Law'), (10, 'Religious'), (11, 'Life_Style'), (12, 'Science'), (13, 'Social_Science'), (14, 'Philosophy'), (15, 'Comic'), (16, 'Children'), (17, 'Art'), (18, 'Encyclopedia'), (19, 'Dictionary'), (20, 'Biography'), (21, 'Horror'), (22, 'Crime'), (23, 'Tragedy'), (24, 'Fairy_Tail'), (25, 'Drama'), (26, 'Fable'), (27, 'Humor'), (28, 'Young_Adult'), (29, 'Play'), (30, 'Political'), (31, 'Math')], max_length=30),
        ),
    ]
