# Generated by Django 3.0.5 on 2020-05-15 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20200514_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.CharField(default="abcdefghij-0", max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
