# Generated by Django 3.0.5 on 2020-05-15 10:34

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to=book.models.create_book_image_upload_path),
        ),
    ]
