# Generated by Django 3.0.5 on 2020-06-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20200627_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors_str',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
