# Generated by Django 3.0.5 on 2020-06-24 08:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0008_auto_20200624_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookExchange',
            fields=[
                ('slug', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('state', models.IntegerField(choices=[(0, 'Requested'), (1, 'Rejected'), (2, 'Started'), (3, 'Delivered'), (4, 'Ended'), (5, 'Closed'), (6, 'Overdue')], default=0)),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date requested')),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date started')),
                ('date_delivered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date delivered')),
                ('date_ended', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date ended')),
                ('request_message', models.CharField(blank=True, max_length=200)),
                ('request_email', models.EmailField(blank=True, max_length=75)),
                ('request_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('response_message', models.CharField(blank=True, max_length=200)),
                ('response_email', models.EmailField(blank=True, max_length=75)),
                ('response_meeting_address', models.CharField(blank=True, max_length=150)),
                ('response_meeting_year', models.CharField(blank=True, max_length=4)),
                ('response_meeting_month', models.CharField(blank=True, max_length=10)),
                ('response_meeting_day', models.CharField(blank=True, max_length=2)),
                ('response_meeting_hour', models.CharField(blank=True, max_length=2)),
                ('response_meeting_minute', models.CharField(blank=True, max_length=2)),
                ('return_meeting_address', models.CharField(blank=True, max_length=150)),
                ('return_meeting_year', models.CharField(blank=True, max_length=4)),
                ('return_meeting_month', models.CharField(blank=True, max_length=10)),
                ('return_meeting_day', models.CharField(blank=True, max_length=2)),
                ('return_meeting_hour', models.CharField(blank=True, max_length=2)),
                ('return_meeting_minute', models.CharField(blank=True, max_length=2)),
                ('lender_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('book_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('borrower_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_exchange', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lend_exchange', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_written', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date written')),
                ('text', models.CharField(max_length=150)),
                ('book_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.BookExchange')),
            ],
        ),
    ]
