# Generated by Django 3.0.5 on 2020-06-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20200624_0632'),
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookexchange',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
    ]
