# Generated by Django 3.0.5 on 2020-06-24 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_auto_20200624_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookexchange',
            name='date_closed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date closed'),
        ),
        migrations.AddField(
            model_name='bookexchange',
            name='date_last_changed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date last changed'),
        ),
    ]
