# Generated by Django 3.0.5 on 2020-06-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_auto_20200601_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookexchange',
            name='date_ended',
            field=models.DateTimeField(blank=True, verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='bookexchange',
            name='date_started',
            field=models.DateTimeField(blank=True, verbose_name='date started'),
        ),
    ]
