# Generated by Django 3.0.5 on 2020-06-01 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_auto_20200601_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookexchange',
            name='date_ended',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='bookexchange',
            name='date_started',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date started'),
        ),
    ]
