# Generated by Django 3.0.5 on 2020-07-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_auto_20200624_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookexchange',
            name='has_borrower_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookexchange',
            name='has_lender_rated',
            field=models.BooleanField(default=False),
        ),
    ]
