# Generated by Django 3.0.5 on 2020-06-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0004_auto_20200601_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookexchange',
            name='response_email',
            field=models.EmailField(blank=True, max_length=75),
        ),
    ]
