# Generated by Django 3.0.5 on 2020-07-09 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20200627_1209'),
        ('sharing', '0004_auto_20200703_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book.Book'),
        ),
    ]
