# Generated by Django 3.0.5 on 2020-07-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0005_comment_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
    ]
