# Generated by Django 3.0.5 on 2020-06-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0005_bookexchange_response_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookexchange',
            name='lender',
        ),
    ]
