# Generated by Django 3.0.5 on 2020-06-03 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharing', '0008_auto_20200603_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookexchange',
            name='lender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lend_exchange', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookexchange',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_exchange', to=settings.AUTH_USER_MODEL),
        ),
    ]
